### ISSUE TITLE
Unable to Run Azlist command

### ISSUE THREAD

**Issue by Dhruv-1982** [magodo/azlist#3]
Hi

I am getting the below error while running the go package

C:\Users\xxxxxxx\azlist-main\azlist-main>go run main.go
#command-line-arguments
.\main.go:34:14: undefined: getVersion

**Comment by magodo** [comment]
@Dhruv-1982 Instead, you shall run `go run . <args>`.

**Comment by Dhruv-1982** [comment]
Go run azlist -s "xxxx" -r 'resourceGroup =~ "xxxxx"' --verbose

Returns
Error: More than one where predicates specified
exit status 1

May be using it wrong?
